import { useState, useEffect } from "react";
import { Loader, Card, FormField } from "../components";

function Home() {
	const [loading, setLoading] = useState(false);
	const [allPosts, setAllPosts] = useState([]);
	const [searchText, setSearchText] = useState("");
	const [searchedResults, setSearchedResults] = useState([]);

	return (
		<section className="text-gray-900">
			<h1 className="text-3xl font-extrabold">The Community Showcase</h1>
			<p className="mt-2 text-base">
				Browse through a collection if imaginative and visually stunning images
				generated by DALLE-E AI
			</p>
			<div className="mt-16">
				{/* @ts-ignore */}
				<FormField />
			</div>
			<div className="mt-10">
				{loading ? (
					<Loader />
				) : (
					<>
						{searchText && (
							<h2 className="mb-3 text-xl font-medium">
								Showing results for{" "}
								<span className="text-green-500">{searchText}</span>{" "}
							</h2>
						)}
						<div className="grid grid-cols-1 gap-4 lg:grid-cols-4 sm:grid-cols-4 xs:grid-cols-2">
							{searchText ? (
								<RenderCard
									data={searchedResults}
									title="No search results found"
								/>
							) : (
								<RenderCard data={allPosts} title="No posts found" />
							)}
						</div>
					</>
				)}
			</div>
		</section>
	);
}

export default Home;

// TODO:
// remove ts-ignore later
// rome-ignore lint/suspicious/noExplicitAny: <explanation>
function RenderCard({ data, title }: { data: any[] | string; title: string }) {
	if (data?.length > 0) {
		// @ts-ignore
		return data.map((post) => <Card key={post._id} {...post} />);
	}

	return <h2 className="mt-5 text-xl font-bold text-blue-800">{title}</h2>;
}
